#!/bin/bash

dir=$(dirname "$(realpath "${BASH_SOURCE}")")

run_until_fail=$dir/run_until_fail

if (($# < 1)); then
    echo "RR output dir not provided" >&2
    exit 1
fi
if ! [[ -d $1 ]]; then
    mkdir -p "$1" || {
        echo "mkdir failed" >&2
        exit 1
    }
fi
rrdir=$(realpath "$1")
shift

if (($# < 1)); then
    echo "Run number not provided" >&2
    exit 1
fi
n=$1
shift

if (($# < 1));then
    echo "Command not provided" >&2
    exit 1
fi

export _RR_TRACE_DIR="$rrdir"

if [[ -n $GC_TEST_BIND_CPU ]]; then
    bind_cpu_arg=(--bind-to-cpu $GC_TEST_BIND_CPU)
else
    bind_cpu_arg=()
fi

if [[ -n $GC_TEST_CHAOS ]]; then
    chaos_arg=(-h)
else
    chaos_arg=()
fi

$run_until_fail "$n" rr record "${chaos_arg[@]}" "${bind_cpu_arg[@]}" --ignore-nested "$@"
